DESCRIPTION="Remove unused space from tables without heavy locks"
REPO="https://github.com/cybertec-postgresql/pg_squeeze.git"
LICENSE="PostgreSQL"
SHARED_PRELOAD="pg_squeeze"
NOTES="Requires shared_preload_libraries = 'pg_squeeze'"
APT_PACKAGE="squeeze"
