DESCRIPTION="PL/pgSQL linter and validator"
REPO="https://github.com/okbob/plpgsql_check.git"
LICENSE="MIT"
VERSION_17="2.10.1"
VERSION_18="2.10.1"
VERSION_19="2.10.1"
SHARED_PRELOAD=""
NOTES=""
APT_PACKAGE="plpgsql-check"
