DESCRIPTION="Statistics collector for WHERE clause predicates"
REPO="https://github.com/powa-team/pg_qualstats.git"
LICENSE="PostgreSQL"
SHARED_PRELOAD="pg_qualstats"
NOTES="Requires shared_preload_libraries = 'pg_qualstats'"
APT_PACKAGE="pg-qualstats"
