DESCRIPTION="PERIODs and SYSTEM VERSIONING for PostgreSQL"
REPO="https://github.com/xocolatl/periods"
LICENSE="PostgreSQL"
SHARED_PRELOAD=""
DEPENDS="btree_gist"
NOTES="Requires btree_gist (installed automatically)."
APT_PACKAGE="periods"
