DESCRIPTION="Automated table partition management for Postgres"
REPO="https://github.com/pgpartman/pg_partman.git"
LICENSE="PostgreSQL"
SHARED_PRELOAD="pg_partman_bgw"
NOTES="Requires shared_preload_libraries = 'pg_partman_bgw' for automatic maintenance"
APT_PACKAGE="partman"
