DESCRIPTION="PostgreSQL privilege escalation with enhanced logging and control"
REPO="https://github.com/pgaudit/set_user"
LICENSE="PostgreSQL"
SHARED_PRELOAD="set_user"
NOTES=""
APT_PACKAGE="set-user"
