DESCRIPTION="Credential checks on user creation and password changes"
REPO="https://github.com/HexaCluster/credcheck.git"
LICENSE="PostgreSQL"
VERSION_17="v5.0"
VERSION_18="v5.0"
VERSION_19="v5.0"
SHARED_PRELOAD="credcheck"
NOTES="Requires shared_preload_libraries = 'credcheck'"
