DESCRIPTION="Oracle-style Global Temporary Tables for PostgreSQL"
REPO="https://github.com/darold/pgtt.git"
LICENSE="ISC"
VERSION_17="v4.5"
VERSION_18="v4.5"
VERSION_19="v4.5"
SHARED_PRELOAD="pgtt"
NOTES="Requires shared_preload_libraries = 'pgtt'"
