DESCRIPTION="Oracle compatibility functions and packages for Postgres"
REPO="https://github.com/orafce/orafce.git"
LICENSE="BSD-0-Clause"
VERSION_17="VERSION_4_16_7"
VERSION_18="VERSION_4_16_7"
VERSION_19="VERSION_4_16_7"
SHARED_PRELOAD=""
NOTES=""
TAG_FILTER="^VERSION_"
