DESCRIPTION="Logical replication slot manager for failover"
REPO="https://github.com/EnterpriseDB/pg_failover_slots.git"
LICENSE="PostgreSQL"
VERSION_17="v1.2.1"
VERSION_18="v1.2.1"
SHARED_PRELOAD="pg_failover_slots"
NOTES="Requires shared_preload_libraries = 'pg_failover_slots'"
