DESCRIPTION="Logical replication slot manager for failover"
REPO="https://github.com/EnterpriseDB/pg_failover_slots.git"
LICENSE="PostgreSQL"
SHARED_PRELOAD="pg_failover_slots"
NOTES="Requires shared_preload_libraries = 'pg_failover_slots'"
APT_PACKAGE="pg-failover-slots"
