DESCRIPTION="PostgreSQL extension providing first and last aggregate functions"
REPO="https://github.com/wulczer/first_last_agg"
LICENSE="PostgreSQL"
SHARED_PRELOAD=""
NOTES=""
APT_PACKAGE="first-last-agg"
