DESCRIPTION="Postgres extension to parse a US street address string"
REPO="https://github.com/postgis/address_standardizer"
LICENSE="MIT"
SHARED_PRELOAD=""
NOTES=""
APT_PACKAGE="address-standardizer"
