DESCRIPTION="Geospatial routing and network analysis on PostGIS"
REPO="https://github.com/pgRouting/pgrouting.git"
LICENSE="GPL-2.0"
SHARED_PRELOAD=""
DEPENDS="postgis"
NOTES="Requires PostGIS to be installed first. Uses Boost Graph library."
APT_PACKAGE="pgrouting"
