DESCRIPTION="System-period temporal tables for Postgres"
REPO="https://github.com/arkhipov/temporal_tables.git"
LICENSE="BSD-2-Clause"
VERSION_17="v1.2.2"
VERSION_18="v1.2.2"
SHARED_PRELOAD=""
NOTES=""
