DESCRIPTION="Incremental View Maintenance for materialized views"
REPO="https://github.com/sraoss/pg_ivm.git"
LICENSE="PostgreSQL"
VERSION_17="v1.14"
VERSION_18="v1.14"
SHARED_PRELOAD=""
NOTES=""
APT_PACKAGE="pg-ivm"
