DESCRIPTION="Tweak execution plans using hints in SQL comments"
REPO="https://github.com/ossc-db/pg_hint_plan.git"
LICENSE="BSD"
VERSION_17="REL17_1_7_1"
VERSION_18="REL18_1_8_0"
SHARED_PRELOAD="pg_hint_plan"
NOTES="Requires shared_preload_libraries = 'pg_hint_plan'"
TAG_FILTER='^REL${PG}_'
APT_PACKAGE="pg-hint-plan"
