DESCRIPTION="Show query plans of currently running PostgreSQL statements"
REPO="https://github.com/cybertec-postgresql/pg_show_plans"
LICENSE="PostgreSQL"
SHARED_PRELOAD="pg_show_plans"
NOTES=""
APT_PACKAGE="show-plans"
