DESCRIPTION="Data anonymization and masking for Postgres"
REPO="https://gitlab.com/dalibo/postgresql_anonymizer.git"
LICENSE="PostgreSQL"
VERSION_17="3.1.3"
VERSION_18="3.1.3"
SHARED_PRELOAD="anon"
NOTES="Requires shared_preload_libraries = 'anon'"
