DESCRIPTION="2-gram full text search (better than trigram for CJK languages)"
REPO="https://github.com/pgbigm/pg_bigm.git"
LICENSE="PostgreSQL"
VERSION_17="v1.2-20250903"
VERSION_18="v1.2-20250903"
SHARED_PRELOAD=""
NOTES=""
