DESCRIPTION="Open-source vector similarity search for Postgres"
REPO="https://github.com/pgvector/pgvector.git"
LICENSE="PostgreSQL"
VERSION_17="0.8.5"
VERSION_18="0.8.5"
VERSION_19="0.8.5"
SHARED_PRELOAD=""
NOTES=""
APT_PACKAGE="pgvector"
