DESCRIPTION="Sampling-based statistics of wait events"
REPO="https://github.com/postgrespro/pg_wait_sampling.git"
LICENSE="PostgreSQL"
SHARED_PRELOAD="pg_wait_sampling"
NOTES="Requires shared_preload_libraries = 'pg_wait_sampling'"
APT_PACKAGE="pg-wait-sampling"
